config/routes.rb
Rails.application.routes.draw do
  resources :producers

  resources :reports

  resources :reporters

  resources :bicycles

  root 'reports#index'

end

app/models/reporter.rb
class Reporter < ActiveRecord::Base
  has_one :bicycle, dependent: :destroy
  belongs_to :report

  accepts_nested_attributes_for :bicycle
end

app/controllers/reporters_controller.rb
class ReportersController < ApplicationController
  before_action :set_reporter, only: [:show, :edit, :update, :destroy]

  # GET /reporters
  # GET /reporters.json
  def index
    @reporters = Reporter.all
  end

  # GET /reporters/1
  # GET /reporters/1.json
  def show
  end

  # GET /reporters/new
  def new
    @reporter = Reporter.new
  end

  # GET /reporters/1/edit
  def edit
  end

  # POST /reporters
  # POST /reporters.json
  def create
    @reporter = Reporter.new(reporter_params)

    respond_to do |format|
      if @reporter.save
        format.html { redirect_to @reporter, notice: 'Reporter was successfully created.' }
        format.json { render :show, status: :created, location: @reporter }
      else
        format.html { render :new }
        format.json { render json: @reporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reporters/1
  # PATCH/PUT /reporters/1.json
  def update
    respond_to do |format|
      if @reporter.update(reporter_params)
        format.html { redirect_to @reporter, notice: 'Reporter was successfully updated.' }
        format.json { render :show, status: :ok, location: @reporter }
      else
        format.html { render :edit }
        format.json { render json: @reporter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reporters/1
  # DELETE /reporters/1.json
  def destroy
    @reporter.destroy
    respond_to do |format|
      format.html { redirect_to reporters_url, notice: 'Reporter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reporter
      @reporter = Reporter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reporter_params
      params.require(:reporter).permit(:name, :last_name, :sex, :email)
    end
end

app/helpers/reporters_helper.rb
module ReportersHelper
end

app/views/reporters/_form.html.haml
= form_for @reporter do |f|
  - if @reporter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reporter.errors.count, "error")} prohibited this reporter from being saved:"
      %ul
        - @reporter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/reporters/edit.html.haml
%h1 Editing reporter

= render 'form'

= link_to 'Show', @reporter
\|
= link_to 'Back', reporters_path

app/views/reporters/index.html.haml
%h1 Listing reporters

%table
  %tr
    %th Name
    %th Last name
    %th Sex
    %th Email
    %th
    %th
    %th

  - @reporters.each do |reporter|
    %tr
      %td= reporter.name
      %td= reporter.last_name
      %td= reporter.sex
      %td= reporter.email
      %td= link_to 'Show', reporter
      %td= link_to 'Edit', edit_reporter_path(reporter)
      %td= link_to 'Destroy', reporter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Reporter', new_reporter_path

app/views/reporters/new.html.haml
%h1 New reporter

= render 'form'

= link_to 'Back', reporters_path

app/views/reporters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @reporter.name
%p
  %b Last name:
  = @reporter.last_name
%p
  %b Sex:
  = @reporter.sex
%p
  %b Email:
  = @reporter.email

= link_to 'Edit', edit_reporter_path(@reporter)
\|
= link_to 'Back', reporters_path