config/routes.rb
Rails.application.routes.draw do
  resources :producers

  resources :reports

  resources :reporters

  resources :bicycles

  root 'reports#index'

end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  belongs_to :reporter
  belongs_to :producer
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]

  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.all
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:producer, :frame_number)
    end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/_form.html.haml
= form_for @bicycle do |f|
  - if @bicycle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bicycle.errors.count, "error")} prohibited this bicycle from being saved:"
      %ul
        - @bicycle.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :producer
    = f.text_field :producer
  .field
    = f.label :frame_number
    = f.text_field :frame_number
  .actions
    = f.submit 'Save'

app/views/bicycles/edit.html.haml
%h1 Editing bicycle

= render 'form'

= link_to 'Show', @bicycle
\|
= link_to 'Back', bicycles_path

app/views/bicycles/index.html.haml
%h1 Listing bicycles

%table
  %tr
    %th Producer
    %th Frame number
    %th
    %th
    %th

  - @bicycles.each do |bicycle|
    %tr
      %td= bicycle.producer
      %td= bicycle.frame_number
      %td= link_to 'Show', bicycle
      %td= link_to 'Edit', edit_bicycle_path(bicycle)
      %td= link_to 'Destroy', bicycle, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bicycle', new_bicycle_path

app/views/bicycles/new.html.haml
%h1 New bicycle

= render 'form'

= link_to 'Back', bicycles_path

app/views/bicycles/show.html.haml
%p#notice= notice

%p
  %b Producer:
  = @bicycle.producer
%p
  %b Frame number:
  = @bicycle.frame_number

= link_to 'Edit', edit_bicycle_path(@bicycle)
\|
= link_to 'Back', bicycles_path