config/routes.rb
Rails.application.routes.draw do
  resources :producers

  resources :reports

  resources :reporters

  resources :bicycles

  root 'reports#index'

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  has_many :bicycles
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render :show, status: :created, location: @producer }
      else
        format.html { render :new }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { render :show, status: :ok, location: @producer }
      else
        format.html { render :edit }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url, notice: 'Producer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:name)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.haml
= form_for @producer do |f|
  - if @producer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@producer.errors.count, "error")} prohibited this producer from being saved:"
      %ul
        - @producer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/producers/edit.html.haml
%h1 Editing producer

= render 'form'

= link_to 'Show', @producer
\|
= link_to 'Back', producers_path

app/views/producers/index.html.haml
%h1 Listing producers

%table
  %tr
    %th Name
    %th
    %th

  - @producers.each do |producer|
    %tr
      %td= producer.name
      %td= link_to 'Show', producer
      %td= link_to 'Edit', edit_producer_path(producer)

%br

= link_to 'New Producer', new_producer_path
|
= link_to 'Back to main page', reports_path

app/views/producers/new.html.haml
%h1 New producer

= render 'form'

= link_to 'Back', producers_path

app/views/producers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @producer.name

  %p
    %b Frame numbers of reported robberies:
    - @producer.bicycles.each do |bicycle|
      %br
      = bicycle.frame_number

= link_to 'Edit', edit_producer_path(@producer)
\|
= link_to 'Back', producers_path