config/routes.rb
Rails.application.routes.draw do
  resources :producers

  resources :reports

  resources :reporters

  resources :bicycles

  root 'reports#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_one :reporter, dependent: :destroy
  has_one :bicycle, through: :reporter

  accepts_nested_attributes_for :reporter
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
    @report.build_reporter
    @report.reporter.build_bicycle

    @producers = Producer.all
  end

  # GET /reports/1/edit
  def edit
    @producers = Producer.all
  end

  # POST /reports
  # POST /reports.json
  def create
    @producers = Producer.all
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @producers = Producer.all
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:description, reporter_attributes: [:name, :last_name, :sex, :email, bicycle_attributes: [:producer_id, :frame_number]])
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg

  %p= "Description"
  .field
    = f.text_area :description

  %br
  %h3= "Reporter data"
  = f.fields_for :reporter do |reporter_attributes|
    .field
      = reporter_attributes.label :name
      = reporter_attributes.text_field :name

    .field
      = reporter_attributes.label :last_name
      = reporter_attributes.text_field :last_name

    .field
      = reporter_attributes.label :sex
      = reporter_attributes.radio_button :sex, "Male", checked: true
      = reporter_attributes.label :male
      = reporter_attributes.radio_button :sex, "Female"
      = reporter_attributes.label :female

    .field
      = reporter_attributes.label :email
      = reporter_attributes.text_field :email

    %br
    %h3= "Bicycle data"
    = reporter_attributes.fields_for :bicycle do |bicycle_attributes|
      .field
        = bicycle_attributes.label :producer
        = bicycle_attributes.collection_select :producer_id, @producers, :id, :name
        = link_to 'Add producer', producers_path

      .field
        = bicycle_attributes.label :frame_number
        = bicycle_attributes.text_field :frame_number
  %br
  .actions
    = f.submit 'Save'

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/index.html.haml
= link_to 'New Report', new_report_path
%h1 Reported robberies

- @reports.each do |report|
  %h3 Report ##{report.id}
  %p
    %b By:
    = report.reporter.name
    = report.reporter.last_name
    (#{report.reporter.sex}, #{report.reporter.email})

  %p
    %b Stolen bicycle:
    = report.bicycle.producer.name
    (Frame number: #{report.bicycle.frame_number})

  %fieldset{:style => "width: 350px"}
    %legend Description
    = report.description

  %p
    = link_to 'Edit', edit_report_path(report)
    |
    = link_to 'Destroy', report, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @report.description
%p
  %b Reporter name:
  = @report.reporter.name
  = @report.reporter.last_name
%p
  %b Reporter sex:
  = @report.reporter.sex
%p
  %b Reporter email:
  = @report.reporter.email
%p
  %b Bicycle producer:
  = @report.bicycle.producer.name
%p
  %b Frame number:
  = @report.bicycle.frame_number

= link_to 'Edit', edit_report_path(@report)
\|
= link_to 'Back', reports_path